# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d5d16653e36c4ba403d42f687a1cce6cd5068ab61b791aeccd2ebd1af92b4aba83ed33d41b521261b753902970c795a01e1b94bd65b7d4f1c082ea26211395

test:
  secret_key_base: daecfcb09b43c612aa5e136bce32cb925fe78dd185caba0f4bdebd5d33fad07e5f14c025582cb5cd5a435d30cec5414fda1a2bb89dcf959884acc786829eb2ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
